# Cascade Configuration File
version: 1.0

# Project specific settings
project:
  name: letter_thief
  description: A Ruby on Rails engine for handling email messages
  language: ruby
  framework: rails

# Code style preferences
style:
  ruby:
    max_line_length: 120
    indent_style: spaces
    indent_size: 2
    documentation: yard

# Test preferences
testing:
  framework: minitest
  coverage_threshold: 90
  approach: tdd
  write_tests_first: true
  fail_on_missing_tests: true

# Git preferences
git:
  commit_message_convention: conventional
  branch_prefix: feature/

# Security
security:
  scan_dependencies: true
  prevent_secrets_in_code: true

# AI behavior
ai:
  auto_format: true
  suggest_improvements: true
  documentation_style: concise
  workflow:
    enforce_tdd: true
    require_tests_before_implementation: true
  code_generation:
    add_comments: true
    add_type_hints: false  # Ruby doesn't typically use type hints
    test_coverage: true
    test_first: true
